format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[aws]
disabled = false
[aws.region_aliases]
eu-west-1 = "euw1"
eu-central-1 = "euc1"

[battery]
charging_symbol = '⚡️ '
discharging_symbol = '💀 '
[[battery.display]]
threshold = 30
style = 'bold yellow'
[[battery.display]]
threshold = 15
style = 'bold red'

[character]
error_symbol = '[✗](bold red) '

[kubernetes]
contexts = [
  { context_pattern = "arn:aws:eks:eu-central-1:445137467319:cluster/main-gha-runner", style = "blue", context_alias = "main-gha-runner" },
]
disabled = false

[memory_usage]
format = 'via $symbol [${ram_pct}( | ${ram})]($style) '
disabled = false
